Imported Upstream version 1.61

diff --git a/usr/share/laptop-mode-tools/modules/usb-autosuspend b/usr/share/laptop-mode-tools/modules/usb-autosuspend
--- a/usr/share/laptop-mode-tools/modules/usb-autosuspend
+++ b/usr/share/laptop-mode-tools/modules/usb-autosuspend
@@ -3,18 +3,60 @@
 # Laptop mode tools module: usb-autosuspend.
 #
 
-blacklisted() {
-	for usbid in $AUTOSUSPEND_USBID_BLACKLIST; do
+# Check whether a USB device is listed by ID
+listed_by_id() {
+	device=$1
+	list=$2
+	for usbid in $list; do
 		if ! echo $usbid | grep -q ':'; then
-			log "MSG" "WARNING: Invalid entry \"$usbid\" in AUTOSUSPEND_USBID_BLACKLIST."
+			log "MSG" "WARNING: Invalid entry \"$usbid\" in \"$2\"."
 		fi
 		vendor=$(echo $usbid | cut -d: -f1)
 		product=$(echo $usbid | cut -d: -f2)
-		grep -qi $vendor $1/idVendor 2>/dev/null\
-		 && grep -qi $product $1/idProduct 2>/dev/null\
+		grep -qi $vendor $device/idVendor 2>/dev/null\
+		 && grep -qi $product $device/idProduct 2>/dev/null\
 		 && return 0
 	done
 	return 1
+}
+
+# Check whether the USB driver type is blacklisted
+listed_by_type() {
+	device=$1
+	device_base=`basename $device`
+	list=$2
+	for driver_type in $list; do
+		if grep -q DRIVER=$driver_type $device/uevent; then
+			return 0
+		fi
+		# Check child devices as well.  The actual driver type is
+		# listed in a child device, not the top-level device.
+		for subdevice in $device/$device_base*; do
+			if [ -f $subdevice/uevent ]; then
+				if grep -q DRIVER=$driver_type\
+				    $subdevice/uevent; then
+					return 0
+				fi
+			fi
+		done
+	done
+	return 1
+}
+
+# Checks whether a device is blacklisted by either ID or driver type
+blacklisted() {
+	listed_by_id $1 "$AUTOSUSPEND_USBID_BLACKLIST"\
+	|| listed_by_type $1 "$AUTOSUSPEND_USBTYPE_BLACKLIST"\
+	|| return 1
+	return 0
+}
+
+# Checks whether a device is whitelisted by either ID or driver type
+whitelisted() {
+	listed_by_id $1 "$AUTOSUSPEND_USBID_WHITELIST"\
+	|| listed_by_type $1 "$AUTOSUSPEND_USBTYPE_WHITELIST"\
+	|| return 1
+	return 0
 }
 
 if [ x$CONTROL_USB_AUTOSUSPEND = x1 ] || [ x$ENABLE_AUTO_MODULES = x1 -a x$CONTROL_USB_AUTOSUSPEND = xauto ]; then
@@ -28,6 +70,23 @@ if [ x$CONTROL_USB_AUTOSUSPEND = x1 ] || [ x$ENABLE_AUTO_MODULES = x1 -a x$CONTR
         SUSPEND_USB_DEVICES="$BATT_SUSPEND_USB"
     fi
 
+    if [ -d /sys/bus/usb/devices ]; then
+	if [ "$DEVICES" != "" ]; then
+		# If a list of devices has been provided, operate on only the
+		# listed USB devices.
+		DEVICE_LIST=""
+		for DEVICE in $DEVICES; do
+			DEVICE_LIST="$DEVICE_LIST $DEVICE"
+		done
+	else
+		# If no list was provided, operate on all USB devices
+		DEVICE_LIST=/sys/bus/usb/devices/*
+	fi
+    else
+	# This will rarely happen.
+	log "VERBOSE" "There are no USB devices."
+    fi
+
     if [ x$SUSPEND_USB_DEVICES = x1 ]; then
 	  if [ -f /sys/module/usbcore/parameters/autosuspend ]; then
 	      echo $AUTOSUSPEND_TIMEOUT > /sys/module/usbcore/parameters/autosuspend
@@ -35,11 +94,27 @@ if [ x$CONTROL_USB_AUTOSUSPEND = x1 ] || [ x$ENABLE_AUTO_MODULES = x1 -a x$CONTR
 	  else
 	      log "VERBOSE" "Not enabling autosuspend mode for USBCORE Controller. Not Supported"
 	  fi
-	  if [ -d /sys/bus/usb/devices ]; then
-	      for usb_device in /sys/bus/usb/devices/*;
-	      do
+
+	  if [ "$DEVICE_LIST" != "" ]; then
+		for usb_device in $DEVICE_LIST; do
 		  usb_device=`basename $usb_device`;
-		  if ! blacklisted /sys/bus/usb/devices/$usb_device; then
+
+		  USE_DEVICE=0
+		  if [ x$AUTOSUSPEND_USE_WHITELIST = x1 ]; then
+			if whitelisted /sys/bus/usb/devices/$usb_device; then
+			  USE_DEVICE=1
+			else
+			  log "VERBOSE" "Device $usb_device not whitelisted, skipping auto suspend."
+			fi
+		  else
+			if ! blacklisted /sys/bus/usb/devices/$usb_device; then
+			  USE_DEVICE=1
+			else
+			  logger "Device $usb_device is blacklisted, skipping auto suspend."
+			fi
+		  fi
+
+		  if [ x$USE_DEVICE = x1 ]; then
 			  if [ -f /sys/bus/usb/devices/$usb_device/power/autosuspend ]; then
 				  echo $AUTOSUSPEND_TIMEOUT > /sys/bus/usb/devices/$usb_device/power/autosuspend;
 				  log "VERBOSE" "Enabling auto suspend mode for usb device $usb_device."
@@ -47,19 +122,17 @@ if [ x$CONTROL_USB_AUTOSUSPEND = x1 ] || [ x$ENABLE_AUTO_MODULES = x1 -a x$CONTR
 				  log "VERBOSE" "Not enabling auto suspend mode for usb device $usb_device"
 			  fi
 
-			  if [ -f /sys/bus/usb/devices/$usb_device/power/level ]; then
+			  if [ -f /sys/bus/usb/devices/$usb_device/power/control ]; then
+				  echo "auto" > /sys/bus/usb/devices/$usb_device/power/control;
+				  log "VERBOSE" "Enabling auto power level for usb device $usb_device."
+			  elif [ -f /sys/bus/usb/devices/$usb_device/power/level ]; then
 				  echo "auto" > /sys/bus/usb/devices/$usb_device/power/level;
 				  log "VERBOSE" "Enabling auto power level for usb device $usb_device."
 			  else
 				  log "VERBOSE" "Not enabling auto power level for usb device $usb_device"
 			  fi
-		  else
-			  log "VERBOSE" "USB device $usbid is in the autosuspend blacklist."
 		  fi
-	      done
-	  else
-	      # This will rarely happen.
-	      log "VERBOSE" "There are no USB devices."
+		done
 	  fi
     else
 	  AUTOSUSPEND_TIMEOUT=0
@@ -69,8 +142,9 @@ if [ x$CONTROL_USB_AUTOSUSPEND = x1 ] || [ x$ENABLE_AUTO_MODULES = x1 -a x$CONTR
 	  else
 	      log "VERBOSE" "Not disabling autosuspend mode for USBCORE Controller. Not Supported"
 	  fi
-	  if [ -d /sys/bus/usb/devices ]; then
-	      for usb_device in /sys/bus/usb/devices/*;
+
+	  if [ "$DEVICE_LIST" != "" ]; then
+	      for usb_device in $DEVICE_LIST;
 	      do
 		  usb_device=`basename $usb_device`;
 		  if [ -f /sys/bus/usb/devices/$usb_device/power/autosuspend ]; then
@@ -80,16 +154,16 @@ if [ x$CONTROL_USB_AUTOSUSPEND = x1 ] || [ x$ENABLE_AUTO_MODULES = x1 -a x$CONTR
 		      log "VERBOSE" "Not disabling auto suspend mode for usb device $usb_device"
 		  fi
 
-		  if [ -f /sys/bus/usb/devices/$usb_device/power/level ]; then
+		  if [ -f /sys/bus/usb/devices/$usb_device/power/control ]; then
+		      echo "on" > /sys/bus/usb/devices/$usb_device/power/control;
+		      log "VERBOSE" "Enabling ON power level for usb device $usb_device."
+		  elif [ -f /sys/bus/usb/devices/$usb_device/power/level ]; then
 		      echo "on" > /sys/bus/usb/devices/$usb_device/power/level;
 		      log "VERBOSE" "Enabling ON power level for usb device $usb_device."
 		  else
 		      log "VERBOSE" "Not enabling ON power level for usb device $usb_device"
 		  fi
 	      done
-	  else
-	      # This will rarely happen.
-	      log "VERBOSE" "There are no USB devices."
 	  fi
     fi
 else
