Bring back the changes.
The problem is with the shell's -e mode.
We can't run in -e mode because we need to probe multiple power management
daemons, amongst which only 1 will return true.

Hence, we don't run our post-inst script in -e mode.

diff --git a/debian/laptop-mode-tools.postinst b/debian/laptop-mode-tools.postinst
--- a/debian/laptop-mode-tools.postinst
+++ b/debian/laptop-mode-tools.postinst
@@ -3,7 +3,10 @@
 #
 # see: dh_installdeb(1)
 
-set -evx
+# We can't run in -e mode because we need to probe the running
+# power management daemons. And thus, leaving one, else all are
+# going to return nothing which as per "set -e" is a failure.
+#set -e
 
 # summary of how this script can be called:
 #        * <postinst> `configure' <most-recently-configured-version>
@@ -32,26 +35,26 @@ case "$1" in
       fi
     fi
 
-    #apm_pid=`pidof apmd`
-    #if [ ! -z $apm_pid ]; then
-    #  if [ -x /etc/init.d/apmd ]; then
-    #    invoke-rc.d apmd force-reload || true
-    #  fi
-    #fi
+    apm_pid=`pidof apmd`
+    if [ ! -z $apm_pid ]; then
+      if [ -x /etc/init.d/apmd ]; then
+        invoke-rc.d apmd force-reload || true
+      fi
+    fi
 
-    #pbbuttonsd_pid=`pidof pbbuttonsd`
-    #if [ ! -z $pbbuttonsd_pid ]; then
-    #  if [ -x /etc/init.d/pbbuttonsd ]; then
-    #    invoke-rc.d pbbuttonsd force-reload || true
-    #  fi
-    #fi
+    pbbuttonsd_pid=`pidof pbbuttonsd`
+    if [ ! -z $pbbuttonsd_pid ]; then
+      if [ -x /etc/init.d/pbbuttonsd ]; then
+        invoke-rc.d pbbuttonsd force-reload || true
+      fi
+    fi
 
-    #pmud_pid=`pidof pmud`
-    #if [ ! -z $pmud_pid ]; then
-    #  if [ -x /etc/init.d/pmud ]; then
-    #    invoke-rc.d pmud force-reload || true
-    #  fi
-    #fi
+    pmud_pid=`pidof pmud`
+    if [ ! -z $pmud_pid ]; then
+      if [ -x /etc/init.d/pmud ]; then
+        invoke-rc.d pmud force-reload || true
+      fi
+    fi
 
   ;;
   abort-upgrade|abort-remove|abort-deconfigure|triggered)
